default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 username: root
 password: root
 host: 127.0.0.1

development:
 <<: *default
 database: image_memories_development

test:
 <<: *default
 database: image_memories_test

production:
 <<: *default
 database: image_memories_production
 password: <%= ENV['WONDERFUL-EDITOR_DATABASE_PASSWORD'] %>
